import { useMemo, useState } from "react";
import { WarningCircle } from "@phosphor-icons/react";
import { buildAdditionEvidenceLedger } from "../../calibration/additionEvidence.js";
import { buildAdditionCorrectionRecommendations } from "../../calibration/additionRecommendations.js";

const STAGE_LABELS = {
  synthetic_only: ["DEMO 전용", "DEMO only"], ledger_only: ["오차 기록 1–9", "Ledger 1–9"], bias_direction: ["방향 참고 10–29", "Direction 10–29"], provisional_candidate: ["임시 후보 30–49", "Provisional 30–49"], validation_set_pending: ["검증 대기 50–69", "Validation pending 50–69"], validation_ready: ["독립 검증 70+", "Holdout validation 70+"],
};

const FIELD_LABELS = {
  fluxAmountMultiplier: ["Flux 양 보정", "Flux amount correction"], coolantAmountMultiplier: ["냉각재 양 보정", "Coolant amount correction"], alloyAmountMultiplier: ["합금·가탄재 양 보정", "Alloy/carburizer amount correction"], oxygenAmountMultiplier: ["산소량 보정", "Oxygen amount correction"],
};

const EXCLUSION_LABELS = {
  slag_result_missing: ["슬래그 실측 없음", "No slag result"], before_analysis_missing: ["투입 전 분석 없음", "No pre-action analysis"], after_analysis_missing: ["투입 후 분석 없음", "No post-action analysis"], confounded_by_other_action: ["다른 조작과 겹침", "Confounded by another action"], effect_value_missing: ["효과 항목 없음", "Effect value missing"], effect_direction_or_outlier: ["방향 반대·극단값", "Opposite direction or outlier"], not_learning_eligible: ["학습 조건 미충족", "Not learning eligible"],
};

function value(value, digits = 3) {
  return Number.isFinite(Number(value)) ? Number(value).toFixed(digits) : "–";
}

export function AdditionLearningPanel({ state, locale, canWrite, onBringCandidate, onOpenRecoveryCard }) {
  const [filter, setFilter] = useState("all");
  const evidence = useMemo(() => buildAdditionEvidenceLedger(state), [state]);
  const recommendations = useMemo(() => buildAdditionCorrectionRecommendations(state, evidence), [state, evidence]);
  const visible = filter === "all" ? evidence : evidence.filter((row) => row.model === filter);
  const eligibleCount = evidence.filter((row) => row.eligible && !row.synthetic).length;
  const ko = locale === "ko";
  return <section className="addition-learning-section" aria-labelledby="addition-learning-title">
    <div className="panel-title addition-learning-title"><div><span>STAGE 3 · OBSERVED EFFECT → REVIEWED COEFFICIENT</span><h2 id="addition-learning-title">{ko ? "투입 코치 오차학습" : "Addition-coach residual learning"}</h2><p>{ko ? "실제 투입 전·후 분석이 있고 다른 투입이 사이에 끼지 않은 기록만 효과 보정 후보에 사용합니다." : "Only isolated actions with before/after analyses are used for effect-correction candidates."}</p></div><button type="button" className="secondary-button" onClick={onOpenRecoveryCard}>{ko ? "투입계수 복구 카드" : "Addition recovery card"}</button></div>
    <div className="learning-health-grid addition-learning-health"><div className="panel"><span>{ko ? "연결된 실제 조작" : "Linked actual actions"}</span><strong>{evidence.length}</strong><small>{ko ? "조작 직전 저장된 코치안과 연결" : "Linked to the pre-action coach snapshot"}</small></div><div className="panel"><span>{ko ? "실제 학습 적격" : "Field-learning eligible"}</span><strong>{eligibleCount}</strong><small>{ko ? "전·후 분석 · 단독 조작 · 효과 방향 정상" : "Before/after · isolated · valid effect direction"}</small></div><div className="panel"><span>{ko ? "추천 후보" : "Correction candidates"}</span><strong>{recommendations.length}</strong><small>{ko ? "30건부터 설정 초안 이동 가능" : "Can move to settings draft from 30 rows"}</small></div><div className="panel"><span>{ko ? "승인 조건 통과" : "Approval gate passed"}</span><strong>{recommendations.filter((item) => item.eligibleForApproval).length}</strong><small>{ko ? "70건·20건 검증·10일·3작업자·3투입구간" : "70 rows · 20 holdout · 10 days · 3 operators · 3 amount bands"}</small></div></div>
    <div className="learning-warning"><WarningCircle weight="fill" /><span>{ko ? "현재 학습은 조작 전후의 관찰 효과를 이용하는 통계 보정입니다. 공정 중 동시 반응을 완전히 분리하지 못하므로 추천은 자동 적용되지 않으며, 현장 검토와 설정 버전 저장이 필요합니다." : "This learning uses observed before/after effects and cannot fully isolate simultaneous process reactions. Candidates are never auto-applied and require field review plus a new settings version."}</span></div>
      <div className="learning-grid"><section className="panel"><div className="panel-title"><h3>{ko ? "투입계수 추천 후보" : "Addition-coefficient candidates"}</h3></div><div className="table-scroll"><table><thead><tr><th>{ko ? "모델/재료" : "Model/material"}</th><th>{ko ? "보정항목" : "Correction"}</th><th>{ko ? "단계·근거" : "Stage/evidence"}</th><th>{ko ? "현재 → 후보" : "Current → candidate"}</th><th>{ko ? "검증 MAE" : "Validation MAE"}</th><th>{ko ? "처리" : "Action"}</th></tr></thead><tbody>{recommendations.map((item) => <tr key={item.id}><td><strong>{item.model}</strong><small>{item.materialCode ?? "OXYGEN"}</small></td><td>{FIELD_LABELS[item.correctionKey]?.[ko ? 0 : 1] ?? item.correctionKey}</td><td><span className={`learning-stage ${item.stage}`}>{STAGE_LABELS[item.stage]?.[ko ? 0 : 1] ?? item.stage}</span><small>{item.count} · {item.distinctDates}{ko ? "일" : " days"} · {item.distinctOperators}{ko ? "명" : " operators"} · {item.distinctOperatingBands}/3 {item.bandKind === "timing" ? (ko ? "시각구간" : "timing bands") : (ko ? "투입구간" : "amount bands")}</small></td><td>{value(item.currentValue)} → <strong>{value(item.candidateValue)}</strong><small>Δ {value(item.recommendedDelta)}</small></td><td>{item.validationCount ? `${value(item.validationBaseline.mae)} → ${value(item.validationCandidate.mae)}` : "–"}</td><td><button type="button" className="table-action" disabled={!canWrite || item.synthetic || !item.versionCurrent || item.count < 30} onClick={() => onBringCandidate(item)}>{ko ? "설정 초안으로" : "To settings draft"}</button></td></tr>)}{!recommendations.length && <tr><td colSpan="6">{ko ? "코치안과 연결된 실제 투입 뒤에 분석값을 입력하면 후보가 생성됩니다." : "Enter analyses after an actual action linked to a coach proposal to build candidates."}</td></tr>}</tbody></table></div></section>
      <section className="panel residual-panel"><div className="panel-title"><h3>{ko ? "투입 효과 오차 대장" : "Addition-effect ledger"}</h3><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">{ko ? "전체 모델" : "All models"}</option>{["flux", "coolant", "alloy", "oxygen"].map((model) => <option key={model} value={model}>{model}</option>)}</select></div><div className="table-scroll"><table><thead><tr><th>{ko ? "차지/조작" : "Heat/action"}</th><th>{ko ? "실제/코치량" : "Actual/coach"}</th><th>{ko ? "항목" : "Item"}</th><th>{ko ? "예상 변화" : "Expected delta"}</th><th>{ko ? "실제 변화" : "Actual delta"}</th><th>{ko ? "학습 판정" : "Learning status"}</th></tr></thead><tbody>{visible.slice(-200).reverse().map((row) => <tr key={row.id}><td><strong>{row.heatId}</strong><small>{row.model} · {row.materialCode ?? "OXYGEN"}</small></td><td>{value(row.actualAmount, 1)} / {value(row.recommendedAmount, 1)} {row.amountUnit}</td><td>{row.element ?? "–"}</td><td>{value(row.expectedDelta, row.element === "temperature" ? 1 : 4)}</td><td>{value(row.actualDelta, row.element === "temperature" ? 1 : 4)}</td><td><span className={`learning-stage ${row.eligible ? "validation_ready" : "ledger_only"}`}>{row.eligible ? (ko ? "적격" : "Eligible") : (EXCLUSION_LABELS[row.exclusionReason]?.[ko ? 0 : 1] ?? row.exclusionReason)}</span>{row.synthetic && <small>DEMO</small>}</td></tr>)}{!visible.length && <tr><td colSpan="6">{ko ? "기록 없음" : "No records"}</td></tr>}</tbody></table></div></section></div>
  </section>;
}
