import { ADDITION_COEFFICIENT_FIELDS, additionCoefficientUnitLabel, materialModelParameters, resolveAdditionProfile } from "../../calculation/addition/additionProfile.js";

const KINDS = ["flux", "coolant", "alloy", "carburizer", "oxygen"];
const STAGES = ["G0", "G1", "G2", "G3", "G4", "G5", "G6", "G7", "G8"];

function optionalNumber(value) {
  return value === "" ? null : Number(value);
}

function kindLabel(kind, ko) {
  const labels = {
    flux: ["Flux", "Flux"], coolant: ["냉각재·광석", "Coolant / ore"], alloy: ["합금철", "Alloy"], carburizer: ["가탄재", "Carburizer"], oxygen: ["추가 산소", "Additional oxygen"],
  };
  return labels[kind]?.[ko ? 0 : 1] ?? kind;
}

export function AdditionProfilesEditor({ draft, setDraft, locale, operatorName, onOpenRecoveryCard }) {
  const ko = locale === "ko";
  const profile = draft.additionModelProfiles?.[0];
  if (!profile) return <div className="validation-errors" role="alert"><strong>{ko ? "투입모델 설정을 불러오지 못했습니다." : "The addition-model settings could not be loaded."}</strong><span>{ko ? "설정 초안을 버리고 다시 열거나 JSON 백업을 복원하십시오." : "Discard the settings draft and reopen it, or restore a JSON backup."}</span></div>;
  const resolved = resolveAdditionProfile(profile);
  const updateProfile = (updater, { preserveStatus = false } = {}) => setDraft((previous) => {
    const next = structuredClone(previous);
    const updated = updater(next.additionModelProfiles[0]);
    next.additionModelProfiles[0] = preserveStatus ? updated : { ...updated, status: "user_modified", approval: null };
    return next;
  });
  const updateCorrection = (key, value) => updateProfile((current) => ({ ...current, corrections: { ...current.corrections, [key]: Number(value) } }));
  const updateValue = (key, value) => updateProfile((current) => ({ ...current, overrideValues: { ...(current.overrideValues ?? {}), [key]: Number(value) } }));
  const updateLimit = (kind, key, value) => updateProfile((current) => ({ ...current, limits: { ...current.limits, [kind]: { ...current.limits[kind], [key]: value } } }));
  const updateMaterial = (code, updater) => updateProfile((current) => ({ ...current, materialOverrides: { ...(current.materialOverrides ?? {}), [code]: updater(structuredClone(current.materialOverrides?.[code] ?? {})) } }));
  const applicableMaterials = draft.materials.filter((material) => ["coolant", "alloy", "carburizer"].includes(material.category));

  function changeStatus(status) {
    updateProfile((current) => ({
      ...current,
      status,
      approval: status === "site_approved" ? { approvedBy: operatorName?.trim() || "", approvedAt: new Date().toISOString(), reason: current.approval?.reason ?? "" } : null,
    }), { preserveStatus: true });
  }

  return <div className="addition-profile-editor">
    <div className="coefficient-heading"><div><h2>{ko ? profile.nameKo : profile.nameEn}</h2><p>{profile.formulaVersion} · {profile.versionId}</p></div><div className="coefficient-heading-actions"><span className={`coefficient-basis-badge ${profile.status}`}>{profile.status === "site_approved" ? (ko ? "현장 승인" : "Site approved") : profile.status === "user_modified" ? (ko ? "사용자 수정·검증 전" : "User modified") : (ko ? "문헌 시험" : "Literature test")}</span><button type="button" className="secondary-button" onClick={onOpenRecoveryCard}>{ko ? "투입계수 복구 카드" : "Addition recovery card"}</button></div></div>
    <div className="addition-model-warning"><strong>{ko ? "기본계수 사용 원칙" : "Default-coefficient policy"}</strong><span>{ko ? "공개 문헌 기본계수로 먼저 계산하지만 현장 승인값은 아닙니다. 실제 오차가 쌓이면 학습 화면에서 후보를 만들고 승인 저장한 새 버전만 적용합니다." : "Public-literature defaults calculate immediately but are not plant-approved. Field residuals create candidates, and only reviewed settings versions are applied."}</span></div>

    <section className="addition-settings-section"><h3>{ko ? "상태와 적용 범위" : "Status and scope"}</h3><div className="settings-form-grid"><label><span>{ko ? "적용 상태" : "Status"}</span><select value={profile.status} onChange={(event) => changeStatus(event.target.value)}><option value="literature_test">{ko ? "문헌 시험" : "Literature test"}</option><option value="user_modified">{ko ? "사용자 수정·검증 전" : "User modified · unvalidated"}</option><option value="site_approved">{ko ? "현장 검증·승인" : "Plant validated · approved"}</option></select></label><label><span>{ko ? "강종 범위" : "Grade scope"}</span><select value={profile.scope?.gradeCode ?? "*"} onChange={(event) => updateProfile((current) => ({ ...current, scope: { ...current.scope, gradeCode: event.target.value } }))}><option value="*">{ko ? "전체" : "All"}</option>{draft.gradeProfiles.map((grade) => <option key={grade.code} value={grade.code}>{grade.code}</option>)}</select></label><label><span>{ko ? "설비 범위" : "Equipment scope"}</span><select value={profile.scope?.equipmentProfileId ?? "*"} onChange={(event) => updateProfile((current) => ({ ...current, scope: { ...current.scope, equipmentProfileId: event.target.value } }))}><option value="*">{ko ? "전체" : "All"}</option>{draft.equipmentProfiles.map((equipment) => <option key={equipment.id} value={equipment.id}>{equipment.id}</option>)}</select></label></div>{profile.status === "site_approved" && <div className="settings-form-grid approval-fields"><label><span>{ko ? "승인자" : "Approver"}</span><input value={profile.approval?.approvedBy ?? ""} onChange={(event) => updateProfile((current) => ({ ...current, approval: { ...current.approval, approvedBy: event.target.value } }), { preserveStatus: true })} /></label><label><span>{ko ? "승인 근거" : "Approval basis"}</span><input value={profile.approval?.reason ?? ""} onChange={(event) => updateProfile((current) => ({ ...current, approval: { ...current.approval, reason: event.target.value } }), { preserveStatus: true })} /></label><label><span>{ko ? "승인 시각" : "Approved at"}</span><input value={profile.approval?.approvedAt ?? ""} readOnly /></label></div>}</section>

    <section className="addition-settings-section"><h3>{ko ? "핵심 보정계수 6개" : "Six core correction coefficients"}</h3><p className="settings-note">{ko ? "초기값은 모두 무보정입니다. ‘배’는 1.000이 무보정이고 1.050은 계산량을 5% 늘리는 뜻입니다. 학습 후보를 승인하거나 비상복구 초안을 저장할 때만 변경하십시오." : "Defaults apply no correction. A multiplier of 1.000 means no correction; 1.050 increases the calculated amount by 5%. Change only through an approved learning candidate or reviewed recovery draft."}</p><div className="addition-coefficient-grid">{ADDITION_COEFFICIENT_FIELDS.map((field) => <label key={field.key}><span>{ko ? field.labelKo : field.labelEn}</span><div className="input-with-unit"><input type="number" min={field.min} max={field.max} step={field.unit === "min" ? 0.1 : 0.001} value={profile.corrections[field.key]} onChange={(event) => updateCorrection(field.key, event.target.value)} /><span>{additionCoefficientUnitLabel(field, locale)}</span></div></label>)}</div></section>

    <section className="addition-settings-section"><h3>{ko ? "문헌 기본 시나리오" : "Literature default scenarios"}</h3><div className="addition-coefficient-grid"><label><span>{ko ? "Flux 염기도 낮음" : "Flux basicity low"}</span><input type="number" min="0.1" step="0.1" value={resolved.values.fluxBasicityLow} onChange={(event) => updateValue("fluxBasicityLow", event.target.value)} /></label><label><span>{ko ? "Flux 염기도 기준" : "Flux basicity base"}</span><input type="number" min="0.1" step="0.1" value={resolved.values.fluxBasicityBase} onChange={(event) => updateValue("fluxBasicityBase", event.target.value)} /></label><label><span>{ko ? "Flux 염기도 높음" : "Flux basicity high"}</span><input type="number" min="0.1" step="0.1" value={resolved.values.fluxBasicityHigh} onChange={(event) => updateValue("fluxBasicityHigh", event.target.value)} /></label><label><span>{ko ? "스크랩 냉각열 기준" : "Scrap cooling reference"}</span><div className="input-with-unit"><input type="number" min="1" step="1" value={resolved.values.scrapCoolingKjPerKg} onChange={(event) => updateValue("scrapCoolingKjPerKg", event.target.value)} /><span>kJ/kg</span></div></label><label><span>{ko ? "광석/스크랩 당량 낮음" : "Ore/scrap equivalent low"}</span><input type="number" min="0.1" step="0.1" value={resolved.values.oreScrapEquivalentLow} onChange={(event) => updateValue("oreScrapEquivalentLow", event.target.value)} /></label><label><span>{ko ? "광석/스크랩 당량 기준" : "Ore/scrap equivalent base"}</span><input type="number" min="0.1" step="0.1" value={resolved.values.oreScrapEquivalentBase} onChange={(event) => updateValue("oreScrapEquivalentBase", event.target.value)} /></label><label><span>{ko ? "광석/스크랩 당량 높음" : "Ore/scrap equivalent high"}</span><input type="number" min="0.1" step="0.1" value={resolved.values.oreScrapEquivalentHigh} onChange={(event) => updateValue("oreScrapEquivalentHigh", event.target.value)} /></label></div></section>

    <section className="addition-settings-section"><h3>{ko ? "조작별 한도와 허용 단계" : "Limits and allowed stages"}</h3><div className="addition-limit-grid">{KINDS.map((kind) => { const limit = profile.limits[kind]; const oxygen = kind === "oxygen"; return <div key={kind} className="addition-limit-card"><div><strong>{kindLabel(kind, ko)}</strong><label className="inline-check"><input type="checkbox" checked={limit.enabled} onChange={(event) => updateLimit(kind, "enabled", event.target.checked)} />{ko ? "사용" : "Enabled"}</label></div><div className="limit-fields"><label><span>{ko ? "최소" : "Min"} ({oxygen ? "Nm³" : "kg"})</span><input type="number" min="0" value={(oxygen ? limit.minNm3 : limit.minKg) ?? ""} onChange={(event) => updateLimit(kind, oxygen ? "minNm3" : "minKg", optionalNumber(event.target.value))} /></label><label><span>{ko ? "최대" : "Max"} ({oxygen ? "Nm³" : "kg"})</span><input type="number" min="0" value={(oxygen ? limit.maxNm3 : limit.maxKg) ?? ""} onChange={(event) => updateLimit(kind, oxygen ? "maxNm3" : "maxKg", optionalNumber(event.target.value))} /></label></div><div className="stage-checkboxes">{STAGES.map((stage) => <label key={stage}><input type="checkbox" checked={limit.allowedStages.includes(stage)} onChange={(event) => updateLimit(kind, "allowedStages", event.target.checked ? [...limit.allowedStages, stage].sort() : limit.allowedStages.filter((item) => item !== stage))} />{stage}</label>)}</div></div>; })}</div></section>

    <section className="addition-settings-section"><h3>{ko ? "재료별 고급값" : "Per-material advanced values"}</h3><p className="settings-note">{ko ? "빈 현장값은 문헌 시험범위를 사용합니다. 재료 로트·수분·입도·용해상태가 바뀌면 별도 재료코드 또는 새 설정버전으로 관리하십시오." : "Blank plant values use literature test ranges. Use a separate material code or settings version when lot, moisture, size, or dissolution state changes."}</p><div className="material-model-list">{applicableMaterials.map((material) => { const params = materialModelParameters(material, resolved); const stored = profile.materialOverrides?.[material.code] ?? {}; return <div key={material.code} className="material-model-card"><div className="material-model-heading"><strong>{material.code} · {ko ? material.nameKo : material.nameEn}</strong><span>{kindLabel(material.category, ko)}</span></div>{material.category === "coolant" && <div className="addition-coefficient-grid">{["low", "base", "high"].map((key) => <label key={key}><span>{ko ? `유효냉각열 ${key}` : `Effective cooling ${key}`}</span><div className="input-with-unit"><input type="number" min="1" step="1" value={stored.coolingKjPerKg?.[key] ?? params.coolingKjPerKg[key]} onChange={(event) => updateMaterial(material.code, (current) => ({ ...current, coolingKjPerKg: { ...(current.coolingKjPerKg ?? {}), [key]: Number(event.target.value) } }))} /><span>kJ/kg</span></div></label>)}</div>}{["alloy", "carburizer"].includes(material.category) && <div className="addition-coefficient-grid"><label><span>{ko ? "주 목표 성분" : "Primary element"}</span><select value={stored.primaryElement ?? params.primaryElement ?? "Mn"} onChange={(event) => updateMaterial(material.code, (current) => ({ ...current, primaryElement: event.target.value }))}>{["C", "Si", "Mn", "P", "S"].map((key) => <option key={key}>{key}</option>)}</select></label>{["low", "base", "high"].map((key) => <label key={key}><span>{ko ? `회수율 ${key}` : `Recovery ${key}`}</span><input type="number" min="0.01" max="1" step="0.01" value={stored.recovery?.[key] ?? params.recovery[key]} onChange={(event) => updateMaterial(material.code, (current) => ({ ...current, recovery: { ...(current.recovery ?? {}), [key]: Number(event.target.value) } }))} /></label>)}<label><span>{ko ? "문헌 용해속도" : "Literature dissolution rate"}</span><div className="input-with-unit"><input type="number" min="0.01" step="0.01" value={stored.dissolutionKgPerSecond ?? params.dissolutionKgPerSecond} onChange={(event) => updateMaterial(material.code, (current) => ({ ...current, dissolutionKgPerSecond: Number(event.target.value) }))} /><span>kg/s</span></div></label></div>}</div>; })}{!applicableMaterials.length && <p>{ko ? "냉각재·합금철·가탄재 분류의 재료를 먼저 등록하십시오." : "Add a coolant, alloy, or carburizer material first."}</p>}</div></section>
  </div>;
}
